In [ ]:
#Encoding categorical features

#Be aware of sparse matrices !
#Missing categorical values -> KNN :)

In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelBinarizer
provinces = ["Wielkopolskie", "Pomorskie", "Lubuskie", "Slaskie"]
label_binarizer = LabelBinarizer()
province_labels = label_binarizer.fit_transform(provinces)
province_labels
#label_binarizer.classes_


array([[0, 0, 0, 1],
       [0, 1, 0, 0],
       [1, 0, 0, 0],
       [0, 0, 1, 0]])

In [2]:
pd.get_dummies(provinces)


Lubuskie  Pomorskie  Slaskie  Wielkopolskie
0         0          0        0              1
1         0          1        0              0
2         1          0        0              0
3         0          0        1              0

In [3]:
from sklearn.preprocessing import MultiLabelBinarizer
cities = ["Poznan", "Gdansk", "Lublin", "Katowice"]
provs_and_cities = list(zip(provinces, cities))
provs_and_cities


[('Wielkopolskie', 'Poznan'),
 ('Pomorskie', 'Gdansk'),
 ('Lubuskie', 'Lublin'),
 ('Slaskie', 'Katowice')]

In [4]:
multi_label_binarizer = MultiLabelBinarizer()
multi_label_binarizer.fit_transform(provs_and_cities)


array([[0, 0, 0, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 1, 0]])

In [ ]:
# Encoding ordinal features


In [5]:
import pandas as pd
df = pd.DataFrame([['apple', 'medium'],
                   ['orange', 'small'], 
                   ['banana', 'large']], 
                  columns=["fruit", "size"])
df

fruit    size
0   apple  medium
1  orange   small
2  banana   large

In [6]:
mapping_dict = {"small": 1,
                "large": 3,
                "medium": 2}
# df['size'] = df['size'].map(mapping_dict)
df['size'] = df['size'].replace(mapping_dict)
df

fruit  size
0   apple     2
1  orange     1
2  banana     3

In [ ]:
#Rescaling the data

    #Log normalization np.log (check the columns variance)
    #MinMaxScaler
    #StandardScaler
    #RobustScaler
#To read:
    #http://benalexkeen.com/feature-scaling-with-scikit-learn/
    #https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html


In [ ]:
#Zadania

#1. Znajdź różnice pomiędzy LabelEncoder, OHE, LabelBinerizer
#2. Zamień wartości w kolumnach tekstowych na typ integer. Zastanów się nad wyborem kolummn.
#3. Przeprowadź skalowanie/standaryzację danych numerycznych (pomiń te z pkt.2) i sprawdź wyniki.
#4. Sprawdź też jaki wpływ ma standaryzacja na KNN, wykorzystany przy uzupełnianiu brakujących danych.

In [3]:
import pandas as pd
import seaborn as sns
import numpy as np

houses = pd.read_csv('houses_data.csv')

In [12]:
houses.select_dtypes(include='object')

Suburb           Address Type Method   SellerG        Date  \
0         Abbotsford      85 Turner St    h      S    Biggin   3/12/2016   
1         Abbotsford   25 Bloomburg St    h      S    Biggin   4/02/2016   
2         Abbotsford      5 Charles St    h     SP    Biggin   4/03/2017   
3         Abbotsford  40 Federation La    h     PI    Biggin   4/03/2017   
4         Abbotsford       55a Park St    h     VB    Nelson   4/06/2016   
...              ...               ...  ...    ...       ...         ...   
13575  Wheelers Hill      12 Strada Cr    h      S     Barry  26/08/2017   
13576   Williamstown     77 Merrett Dr    h     SP  Williams  26/08/2017   
13577   Williamstown       83 Power St    h      S     Raine  26/08/2017   
13578   Williamstown      96 Verdon St    h     PI   Sweeney  26/08/2017   
13579     Yarraville        6 Agnes St    h     SP   Village  26/08/2017   

      CouncilArea                  Regionname  
0           Yarra       Northern Metropolitan  
1           Yarra       Northern Metropolitan  
2           Yarra       Northern Metropolitan  
3           Yarra       Northern Metropolitan  
4           Yarra       Northern Metropolitan  
...           ...                         ...  
13575         NaN  South-Eastern Metropolitan  
13576         NaN        Western Metropolitan  
13577         NaN        Western Metropolitan  
13578         NaN        Western Metropolitan  
13579         NaN        Western Metropolitan  

[13580 rows x 8 columns]

In [16]:
houses.CouncilArea.unique()

array(['Yarra', 'Moonee Valley', 'Port Phillip', 'Darebin', 'Hobsons Bay',
       'Stonnington', 'Boroondara', 'Monash', 'Glen Eira', 'Whitehorse',
       'Maribyrnong', 'Bayside', 'Moreland', 'Manningham', 'Banyule',
       'Melbourne', 'Kingston', 'Brimbank', 'Hume', nan, 'Knox',
       'Maroondah', 'Casey', 'Melton', 'Greater Dandenong', 'Nillumbik',
       'Whittlesea', 'Frankston', 'Macedon Ranges', 'Yarra Ranges',
       'Wyndham', 'Cardinia', 'Unavailable', 'Moorabool'], dtype=object)

In [17]:
houses.Regionname.unique()

array(['Northern Metropolitan', 'Western Metropolitan',
       'Southern Metropolitan', 'Eastern Metropolitan',
       'South-Eastern Metropolitan', 'Eastern Victoria',
       'Northern Victoria', 'Western Victoria'], dtype=object)

In [15]:
from sklearn.preprocessing import LabelBinarizer
regionname = houses['Regionname']
label_binarizer = LabelBinarizer()
regionname_labels = label_binarizer.fit_transform(regionname)
regionname_labels

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0]])

In [23]:
from sklearn.preprocessing import LabelEncoder


In [27]:
le = preprocessing.LabelEncoder()
le.fit(houses['Regionname'])
LabelEncoder()
list(le.classes_)
le.transform(houses['Regionname'])
list(le.inverse_transform([2, 3, 1]))

['Northern Metropolitan', 'Northern Victoria', 'Eastern Victoria']

In [ ]:
# + konweracja i linki z zooma

czy tylko ja słyszę charczący i przerywający mikrofon Pana Michała?
From Sławomir Kranc to Everyone:  11:51 AM
tylko ty
wszystko jest w porzadku
From Iwona K to Everyone:  11:51 AM
ja dobrze słyszę
From astodolski@edu.cdv.pl to Everyone:  11:51 AM
dobrze jest
From Michał Klimas to Everyone:  11:57 AM
From typing import List, Tuple
def read_csv_file(file_name: str) -> pd.Dataframe:
List[str], Tuple[int, str]
From Andrzej Stawicki to Everyone:  12:10 PM
ok
From Michał Klimas to Everyone:  12:18 PM
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.select_dtypes.html
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.median_absolute_deviation.html
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.clip.html
https://numpy.org/doc/stable/reference/generated/numpy.percentile.html
From Sławomir Kranc to Everyone:  12:21 PM
ok to działamy
From Michał Klimas to Everyone:  12:49 PM
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.query.html
& |
From Michał Klimas to Everyone:  12:59 PM
https://www.coursera.org/learn/machine-learning
From Michał Klimas to Everyone:  01:06 PM
https://jamboard.google.com/d/1zvyRx8BVp7OXSkLCs_jl3zeOyqap58J6X1HUboSv72M/edit?usp=sharing
From Michał Klimas to Everyone:  01:18 PM
def mean_test(column):
    col_mean = column.mean()
    return column < col_mean
test_df.apply(lambda x: mean_test(x))
From Michał Klimas to Everyone:  01:44 PM
def modified_z_score_outlier(column):    
    mad_column = median_abs_deviation(column)
    median = np.median(column)
    mad_score = np.abs(0.6745 * (column - median) / mad_column)
    return mad_score > 3.5
https://www.itl.nist.gov/div898/handbook/eda/section3/eda35h.htm
From Iwona K to Everyone:  01:45 PM
myślę żeby iść dalej
From Michał Klimas to Everyone:  01:48 PM
https://pastebin.com/ZyUM3dYf
From Michał Klimas to Everyone:  01:54 PM
https://chrisalbon.com/
From Andrzej Stawicki to Everyone:  01:55 PM
nie robiliśmy
From Sławomir Kranc to Everyone:  02:26 PM
28 chyba
From Michał Klimas to Everyone:  02:30 PM
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error
from sklearn.linear_model import LinearRegression
 
X_train, X_test, y_train, y_test = train_test_split(houses_predictors, 
                                                    houses_target,
                                                    train_size=0.7, 
                                                    test_size=0.3, 
                                                    random_state=0)
 
def score_dataset(X_train, X_test, y_train, y_test):
  regr_model = LinearRegression()
  regr_model.fit(X_train, y_train)
  preds = regr_model.predict(X_test)
  return mean_absolute_error(y_test, preds)
From Michał Klimas to Everyone:  02:40 PM
Wracam za chwile
jestem
From Andrzej Stawicki to Everyone:  02:44 PM
a co powinien zwrócić ten kod wyżej? jedną liczbę?
From Michał Klimas to Everyone:  02:48 PM
Jedna liczba
https://scikit-learn.org/stable/modules/generated/sklearn.metrics.mean_absolute_error.html#sklearn.metrics.mean_absolute_error
Możliwe jest zastosowanie multioutput, wtedy trzeba podać argument “raw_values”
From Michał Klimas to Everyone:  03:09 PM
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isna.html
https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html
From Sławomir Kranc to Everyone:  03:30 PM
Postępy u mnie: skończyłem te krótkie funkcje. Trochę czasu zajmuje zanim załapie się dokładnie jakie powinna przyjmować argumenty
każda z metod
From Michał Klimas to Everyone:  03:31 PM
Ok, dziękuję
From Sławomir Kranc to Everyone:  03:36 PM
dobrze
From Andrzej Stawicki to Everyone:  04:20 PM
tak
From Sławomir Kranc to Everyone:  04:20 PM
ja jestem w trakcie :D
From Andrzej Stawicki to Everyone:  04:20 PM
udało się
From Dawid Jaskulski to Everyone:  04:21 PM
MAE for LinearRegression and RandomForestRegressor [279454.6, 179045.15]
przy dropna axis 0
From Andrzej Stawicki to Everyone:  04:23 PM
możemy iść dalej:)
From Dawid Jaskulski to Everyone:  04:23 PM
Jeśli koledzy nie mają nic przeciwko to możemy iść dalej
From Mikołaj Klawitter to Everyone:  04:24 PM
zw
From Andrzej Stawicki to Everyone:  04:25 PM
Forest się dużo dłużej przelicza:)
From Mikołaj Klawitter to Everyone:  04:26 PM
jj
From Michał Klimas to Everyone:  04:38 PM
https://chrisalbon.com/machine_learning/preprocessing_structured_data/handling_outliers/
From Michał Klimas to Everyone:  04:51 PM
Wracam za chwile
From Michał Klimas to Everyone:  05:05 PM
Hasło do kursu ML:
ML-niestacj-2021
https://moodle.cdv.pl/course/view.php?id=1889
From Sławomir Kranc to Everyone:  05:07 PM
również potwierdzam
From Michał Klimas to Everyone:  05:12 PM
ML-niestacj-2021
https://moodle.cdv.pl/course/view.php?id=1889
From Sławomir Kranc to Everyone:  05:25 PM
bardzo fajnie to wygląda
From Iwona K to Everyone:  05:26 PM
ja polecam yt:
https://www.youtube.com/c/joshstarmer/featured
From Dawid Jaskulski to Everyone:  05:32 PM
trochę po za tematem ML: https://www.statystyczny.pl/
statystyka w formie map myśli 
https://stackoverflow.com/questions/50473381/scikit-learns-labelbinarizer-vs-onehotencoder
From Me to Everyone:  05:32 PM
dziekuje! :)
From Sławomir Kranc to Everyone:  05:35 PM
https://datascience.stackexchange.com/questions/9443/when-to-use-one-hot-encoding-vs-labelencoder-vs-dictvectorizor
